[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions"

[[plugins]]
  package = "@netlify/plugin-astro"

# Ignore Dependabot PRs from auto-deployment
[build.ignore]
  # Skip deploy for Dependabot branches
  command = "if [[ $HEAD == dependabot/* ]]; then exit 1; else exit 0; fi"