[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions-internal"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com https://api.netlify.com https://*.netlify.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: blob: https:;
      media-src 'self';
      connect-src 'self' https://identity.netlify.com https://api.netlify.com https://*.netlify.com https://github.com https://unpkg.com;
      frame-src 'self' https://identity.netlify.com https://github.com;
      base-uri 'self';
      form-action 'self';
      upgrade-insecure-requests;
    """

[[redirects]]
  from = "/.netlify/identity/*"
  to = "https://identity.netlify.com/.netlify/identity/:splat"
  status = 200
  force = true

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept"