[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions"

[[plugins]]
  package = "@astrojs/netlify/functions"

# Ignore Dependabot PRs from auto-deployment
[built.ignore]
  # Skip deploy for Dependabot branches
  command = "if [[ $HEAD == dependabot/* ]]; then exit 1; else exit 0; fi"