[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions-internal"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "false"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = """
      default-src 'self' https:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com;
      style-src 'self' 'unsafe-inline' https://unpkg.com;
      img-src 'self' data: https: blob:;
      media-src 'self' data: https: blob:;
      connect-src 'self' https://api.netlify.com https://api.github.com data: blob: https:;
      frame-src 'self' https://identity.netlify.com;
      base-uri 'self';
      form-action 'self'
    """

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"