[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions"
  ignore = "if [[ $HEAD == dependabot/* ]]; then exit 1; else exit 0; fi"

[[edge_functions]]
  function = "entry"
  path = "/*"