[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions"
  ignore = "if [[ $HEAD == dependabot/* ]]; then exit 1; else exit 0; fi"

[[edge_functions]]
  function = "entry"
  path = "/*"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/admin/*"
  [headers.values]
    # Essential security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'; default-src 'self' https://identity.netlify.com https://unpkg.com; script-src 'self' 'unsafe-inline' https://identity.netlify.com https://unpkg.com; style-src 'self' 'unsafe-inline' https://unpkg.com; img-src 'self' data: https://unpkg.com; connect-src 'self' https://api.netlify.com;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false